### ISSUE TITLE
crashes after ~30s of being in main menu or by joining a map

### ISSUE THREAD

**Issue by pinhagh** [4wi/i_was_coding_this_while_drunk#11]
cheat shows the menu but crashes a while after or when i try to join a map

**Comment by pinhagh** [comment]
![image](https://user-images.githubusercontent.com/88907266/173852858-a3d725dc-7988-4567-b5a8-5204ee480128.png)

**Comment by SandFoxy** [comment]
I have this problem too

**Comment by pinhagh** [comment]
fixed it by adding binary path, cheat injects and shows menu but crashes after a while

**Comment by pinhagh** [comment]
![image](https://user-images.githubusercontent.com/88907266/173861264-0657d862-dd23-452c-bfee-5d06e14dd5a9.png)
this happened when injecting the debug monolith dll to csgo, dunno why but when injecting the release one csgo doesnt crash instantly
