### ISSUE TITLE
Cannot include hde64.h, no file such

### ISSUE THREAD

**Issue by astronomy474** [4wi/i_was_coding_this_while_drunk#15]
Trying to compile the steam_module. Keep getting the same error and its as basic as that, looked in the minhook/hde folder and couldnt find a hde64.h myself, so was wondering what i should do.

**Comment by pinhagh** [comment]
compile it in release x86 (or debug x86 if ur debugging) and use these settings
![image](https://user-images.githubusercontent.com/88907266/173861883-cffad773-a063-47ee-857b-0037e868bc83.png)

**Comment by astronomy474** [comment]
could u add my discord ku#9999 to help? im actually clueless.

**Comment by aleksandar-yordanov** [comment]
> Trying to compile the steam_module. Keep getting the same error and its as basic as that, looked in the minhook/hde folder and couldnt find a hde64.h myself, so was wondering what i should do.

change .h to .hpp. file should be there but as an hpp file

**Comment by astronomy474** [comment]
still cant get it to work, injecting the dll does literally nothing.

**Comment by violanes** [comment]
@ku1337 if you inject dll using remote LoadLibrary you need to start game with -insecure option otherwise you should inject it via manual mapping

**Comment by astronomy474** [comment]
@violanes could u contact me on discord? the steam_module does nothing when injecting. My discord is ku#9999

**Comment by pinhagh** [comment]
> @violanes could u contact me on discord? the steam_module does nothing when injecting. My discord is ku#9999

its not meant to
you have to launch steam, inject steam module, open local server, open csgo then inject monolith.dll

**Comment by astronomy474** [comment]
isnt it supposed to show a init cmd?

**Comment by astronomy474** [comment]
can someone just add my discord for support rq LMFAO

**Comment by astronomy474** [comment]
still found no solution.
