### ISSUE TITLE
Crash while joining to the map

### ISSUE THREAD

**Issue by certeas** [4wi/i_was_coding_this_while_drunk#3]
Hello dear devs.
I was changed ws protocol to win tcp, and ive got crash while joining to the map, i think this hack is outdated. Do you plan to update it for current versions of csgo or not?

**Comment by nstify** [comment]
@certeas can you help me about injection

**Comment by nstify** [comment]
@certeas can you help me about ws protocol to win tcp ?

**Comment by violanes** [comment]
@certeas you would need to update CInput structure offsets (in_thirdperson, cam_angles, cmd etc)
input pointer is stored in interface pointers array (0x229C5C90) with offset 0x2C (index 11). GetUsercmd as well as GetVerifiedCmd are not inlined and really easy to update, the correct fix is provided in the latest commit.

Gl on updating other stuff, feel free to contribute!

@nstify changed ws to wintcp in connection routine, you need achieve request handling yourself. All required functions and libraries are already presented and linked

**Comment by ghost** [comment]
@violanes thank you sir.
