### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by yarz9** [4wi/i_was_coding_this_while_drunk#6]
first error: could not open 'C:\Program Files (x86)\vcpkg\installed\x86-windows\debug\lib\*.lib': invalid argument	monolith	C:\Users\duvnj\Desktop\i_was_coding_this_while_drunk-master\monolith\lld-link	1	
second error: VirtualizerSDK.h file not found
third error: cannot open source file "VirtualizerSDK.h"

**Comment by asm00009** [comment]
i get the second error too

**Comment by asm00009** [comment]
its fixed for me now. Now the only problem is that steam crashes
